services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        secrets:
            - mongo_uri
secrets:
    mongo_uri:
        file: ./secrets/mongo-uri.txt
