services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "4000:4000"
        secrets:
            - mongo_uri
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - backend

secrets:
    mongo_uri:
        file: ./secrets/mongo-uri.txt
