name: Backend | Run (ts-node)

on: [push, pull_request]

jobs:
  formatting-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./portfolio-backend
        run: npm install

      - name: Run the project
        working-directory: ./portfolio-backend
        env:
          PORT: 3000
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          nohup npm run start &
          sleep 3