name: Backend | Run (ts-node)

on: [push, pull_request]

jobs:
    run:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.7

            - name: Set up Node.js
              uses: actions/setup-node@v4.0.3
              with:
                  node-version: 20

            - name: Install dependencies
              working-directory: ./backend
              run: npm install

            - name: Run the project
              working-directory: ./backend
              env:
                  PORT: 3000
                  MONGO_URI: ${{ secrets.MONGO_URI }}
              run: |
                  nohup npm run start &
                  sleep 3
